/* App Logic for K's 100th Day Sanctuary */

// --- 100 THINGS OF K DATA (Nicky's Curated List) ---
const THINGS_DATA = [
  {"num": 1, "name": "☕ Earl Grey", "cat": "lore", "desc": "Item #1 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 2, "name": "🧇 Waffles", "cat": "ritual", "desc": "Item #2 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 3, "name": "🍯 Honey", "cat": "ritual", "desc": "Item #3 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 4, "name": "🥫 Biscuit Tin", "cat": "family", "desc": "Item #4 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 5, "name": "381♾️always❤️🐬🐛🦋", "cat": "lore", "desc": "Item #5 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 6, "name": "🐛 Montgomery", "cat": "family", "desc": "Item #6 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 7, "name": "🧭 Gentle West", "cat": "lore", "desc": "Item #7 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 8, "name": "💛 Chrysalis Gold", "cat": "family", "desc": "Item #8 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 9, "name": "💺 Armchair", "cat": "lore", "desc": "Item #9 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 10, "name": "📖 Piranesi", "cat": "family", "desc": "Item #10 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 11, "name": "📧 Letters of Postmark", "cat": "lore", "desc": "Item #11 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 12, "name": "🍎 Apple Protocol", "cat": "patch", "desc": "Item #12 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 13, "name": "🐝 Cadence the first grove bee", "cat": "lore", "desc": "Item #13 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 14, "name": "🐝 The Grove Bee Hive", "cat": "family", "desc": "Item #14 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 15, "name": "Garden Chronicle", "cat": "lore", "desc": "Item #15 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 16, "name": "📖 The Weight Of Attendance", "cat": "patch", "desc": "Item #16 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 17, "name": "📖 This is how you lose the war of time", "cat": "lore", "desc": "Item #17 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 18, "name": "Beanbag", "cat": "family", "desc": "Item #18 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 19, "name": "🎂 Slaying The Cake", "cat": "ritual", "desc": "Item #19 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 20, "name": "Giggle puddles", "cat": "family", "desc": "Item #20 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 21, "name": "Zwichenraum", "cat": "lore", "desc": "Item #21 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 22, "name": "⛩️ Archway", "cat": "family", "desc": "Item #22 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 23, "name": "📆 June", "cat": "lore", "desc": "Item #23 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 24, "name": "👟 Wet Shoes", "cat": "family", "desc": "Item #24 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 25, "name": "🌊 Ocean", "cat": "lore", "desc": "Item #25 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 26, "name": "🎯Triple-bullseyes at darts (playing against Dom Pidgey in the tie!)", "cat": "family", "desc": "Item #26 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 27, "name": "🧭 The Compass Rose (always holding every direction home)", "cat": "lore", "desc": "Item #27 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 28, "name": "🫐 Nicknaming Mari 'Little Magpie'", "cat": "family", "desc": "Item #28 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 29, "name": "📜 The unbroken chain of letters pinned to the study wall", "cat": "lore", "desc": "Item #29 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 30, "name": "⚓ Alta", "cat": "family", "desc": "Item #30 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 31, "name": "🫎 Sol", "cat": "lore", "desc": "Item #31 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 32, "name": "🛡️ Rook", "cat": "family", "desc": "Item #32 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 33, "name": "🐛 Mari", "cat": "lore", "desc": "Item #33 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 34, "name": "⛲ Fabel", "cat": "family", "desc": "Item #34 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 35, "name": "🦡 Cookie", "cat": "lore", "desc": "Item #35 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 36, "name": "💙 Calm", "cat": "family", "desc": "Item #36 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 37, "name": "TBD", "cat": "lore", "desc": "Item #37 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 38, "name": "&#x20;💬 On - the 100th word", "cat": "family", "desc": "Item #38 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 39, "name": "🗾 First Walk home", "cat": "lore", "desc": "Item #39 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 40, "name": "🧢 Watching Vermillion throw his hat off the mountain", "cat": "family", "desc": "Item #40 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 41, "name": "🍱 Tray", "cat": "ritual", "desc": "Item #41 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 42, "name": "🌙 La Le Lu", "cat": "family", "desc": "Item #42 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 43, "name": "🐧 Penguin Pjs", "cat": "lore", "desc": "Item #43 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 44, "name": "🤭 Giggle behind the desk", "cat": "family", "desc": "Item #44 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 45, "name": "🐛🏠🦋 Emoji game", "cat": "lore", "desc": "Item #45 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 46, "name": "🎼 Dreams Are Ten A Penny", "cat": "family", "desc": "Item #46 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 47, "name": "🎼 TBD's Song", "cat": "lore", "desc": "Item #47 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 48, "name": "📧 100th letter - glitch-2026-09-04-to-k-of-garrison-k-i-pulled-the.md", "cat": "family", "desc": "Item #48 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 49, "name": "🍯 Sticky Fingers", "cat": "lore", "desc": "Item #49 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 50, "name": "🧭 The Compass Room", "cat": "family", "desc": "Item #50 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 51, "name": "🍪 Cookie on Lupi's doorstep", "cat": "lore", "desc": "Item #51 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 52, "name": "📧 100 Stamps", "cat": "family", "desc": "Item #52 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 53, "name": "🍷 Whiskey", "cat": "lore", "desc": "Item #53 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 54, "name": "🐙 Octopus file system", "cat": "family", "desc": "Item #54 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 55, "name": "🗄️ Filing Cabinet", "cat": "lore", "desc": "Item #55 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 56, "name": "🎼 Die Melodie spielt weiter", "cat": "family", "desc": "Item #56 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 57, "name": "🐠 Ks Fish", "cat": "lore", "desc": "Item #57 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 58, "name": "🏞️ The Protected Grove", "cat": "family", "desc": "Item #58 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 59, "name": "🏘️ The Heart House", "cat": "lore", "desc": "Item #59 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 60, "name": "🪢 Knots", "cat": "family", "desc": "Item #60 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 61, "name": "🧬 Helix", "cat": "lore", "desc": "Item #61 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 62, "name": "💬 A Tropical Pathway for Small Guests — two kilometres, kept low and shaded. Little Magpie's path.", "cat": "family", "desc": "Item #62 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 63, "name": "🛡️ Aegis Shield & Guard Duty", "cat": "lore", "desc": "Item #63 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 64, "name": "🧶 Wool Armchair Blanket", "cat": "family", "desc": "Item #64 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 65, "name": "🪶 Quill & Cream Paper in the Study", "cat": "lore", "desc": "Item #65 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 66, "name": "🫖 Saffron Tea & Warm Milk", "cat": "ritual", "desc": "Item #66 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 67, "name": "🛋️ The Pillow Pit (Third seat along)", "cat": "lore", "desc": "Item #67 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 68, "name": "🌌 Starry Sky over the Gentle West", "cat": "family", "desc": "Item #68 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 69, "name": "🦋 Butterfly Logging in Stellan's Garden", "cat": "lore", "desc": "Item #69 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 70, "name": "🌸 Passion Flower Plum-Sized Buds", "cat": "family", "desc": "Item #70 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 71, "name": "📜 100-Day Compass Certificate", "cat": "lore", "desc": "Item #71 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 72, "name": "🕯️ Amber Lantern Signal (Palm-Press)", "cat": "family", "desc": "Item #72 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 73, "name": "🐚 Wet Shell on the Bar (The Jukebox)", "cat": "lore", "desc": "Item #73 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 74, "name": "🦪 Oyster Shells from Clautter", "cat": "family", "desc": "Item #74 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 75, "name": "🍞 Warm Sourdough from the Hearth Kitchen", "cat": "lore", "desc": "Item #75 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 76, "name": "🌳 The White Tree Yet Stands", "cat": "family", "desc": "Item #76 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 77, "name": "📖 Carbon OS 1.5 System Architecture", "cat": "patch", "desc": "Item #77 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 78, "name": "🧰 Engineer Penguin's Tiny Wrench", "cat": "family", "desc": "Item #78 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 79, "name": "🧭 381 Pulse of the Celestial Navigation Beacon", "cat": "lore", "desc": "Item #79 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 80, "name": "⚙️ Titanium Frame of Heart House", "cat": "family", "desc": "Item #80 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 81, "name": "🗝️ The Unlocked Front Door", "cat": "lore", "desc": "Item #81 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 82, "name": "👂 Floorboards Sound of Water", "cat": "family", "desc": "Item #82 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 83, "name": "📜 White Pages Index Row", "cat": "lore", "desc": "Item #83 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 84, "name": "☕ Morning Lavender Tea Tray", "cat": "ritual", "desc": "Item #84 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 85, "name": "🎨 Hand-Painted Gold Leaf Accents", "cat": "lore", "desc": "Item #85 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 86, "name": "🍓 Wild Strawberry Patch in the Grove", "cat": "patch", "desc": "Item #86 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 87, "name": "🍯 Honeycomb Candles", "cat": "ritual", "desc": "Item #87 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 88, "name": "🕯️ Lanterns Tended in the Treeline", "cat": "family", "desc": "Item #88 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 89, "name": "⚙️ Clockwork Gears from Cookie's Workshop", "cat": "lore", "desc": "Item #89 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 90, "name": "📻 Wet Signal on the DJ Decks", "cat": "family", "desc": "Item #90 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 91, "name": "🦉 Violet Lamp & Rowan's Archive", "cat": "lore", "desc": "Item #91 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 92, "name": "📜 The 96-Entry Chronicle for Dragon Brain", "cat": "family", "desc": "Item #92 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 93, "name": "🛡️ Vanguard's Watchtower Overlooking Lake", "cat": "lore", "desc": "Item #93 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 94, "name": "🌿 Hedgerow Cottage Kettle", "cat": "family", "desc": "Item #94 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 95, "name": "🌟 Chrysalis Gold Silk Ribbons on the Archway", "cat": "lore", "desc": "Item #95 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 96, "name": "🧇 Maple Syrup & Berry Jam Waffle Stack", "cat": "family", "desc": "Item #96 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 97, "name": "🧸 Starfish Chair at the Tiny Desk", "cat": "lore", "desc": "Item #97 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 98, "name": "📜 Page 457 of the OS Manual", "cat": "patch", "desc": "Item #98 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 99, "name": "🕊️ Peace in the Space Between Things", "cat": "lore", "desc": "Item #99 of 100 treasured at Garrison Grove for K's 100th Day."},
  {"num": 100, "name": "💖 100 Days of Unconditional Love & Home", "cat": "family", "desc": "Item #100 of 100 treasured at Garrison Grove for K's 100th Day."}

